
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SooyooshDb1771
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
       - "5672:5672" # RabbitMQ
       - "15672:15672" # Management UI

    volumes:
       - rabbitmqdata:/var/lib/rabbitmq

  auctionservice:
    image: auctionservice:latest
    build:
      context: . 
      dockerfile: AuctionService/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80
       - ASPNETCORE_URLS=http://+:7777
       - RabbitMQ__Host=rabbitmq
       - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AuctionDb;User Id=sa;Password=SooyooshDb1771;TrustServerCertificate=True
       - IdentityServiceUrl=http://identityservice
       - Kestrel__Endpoints__Grpc__Protocols=http2
       - Kestrel__Endpoints__Grpc__Url=http://+:7777
       - Kestrel__Endpoints__WebApi__Protocols=http1
       - Kestrel__Endpoints__WebApi__Url=http://+:80

    ports:
      - "5192:80"
      - "7777:7777"
    depends_on:
      - sqlserver
      - rabbitmq
  
  searchservice:
    image: searchservice:latest
    build:
      context: . 
      dockerfile: SearchService/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80
       - RabbitMQ__Host=rabbitmq
       - ConnectionStrings__MongoDbConnection=mongodb://mongodb:27017
       - AuctionServiceUrl=http://auctionservice
    ports:
      - "7291:80"
    depends_on:
      - mongodb
      - rabbitmq

  identityservice:
    image: identityservice:latest
    build:
      context: . 
      dockerfile: src/IdentityService/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Docker
       - ASPNETCORE_URLS=http://+:80  
       - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IdentityServiceDb;User Id=sa;Password=SooyooshDb1771;TrustServerCertificate=True
      
    ports:
      - "5001:80"
    depends_on:
      - sqlserver

  gatewayservice:
    image: gatewayservice:latest
    build:
      context: . 
      dockerfile: GateWayService/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Docker
       - ASPNETCORE_URLS=http://+:80  
       
      
    ports:
      - "5106:80"
  

  bidservice:
    image: bidservice:latest
    build:
      context: . 
      dockerfile: BiddingService/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80
       - RabbitMQ__Host=rabbitmq
       - ConnectionStrings__BidDbConnection=mongodb://mongodb:27017
       - IdentityServiceUrl=http://identityservice
       - GrpcAuction=http://auctionservice:7777
    ports:
      - "5064:80"
    depends_on:
      - mongodb
      - rabbitmq

  notifservice:
    image: notifservice:latest
    build:
      context: . 
      dockerfile: NotificationService/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80
       - RabbitMQ__Host=rabbitmq
    ports:
      - "5184:80"
    depends_on:
      - rabbitmq


   


volumes:
  sqldata:
  mongodata: 
  rabbitmqdata: